name: tractian
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  logger: ^2.4.0
  mobx: ^2.3.3+2
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
